# change the passwords and use https://docs.docker.com/compose/environment-variables/
# to keep sensitives value in a .env file while using ${VAR_NAME} here instead

services:
  api:
    image: "ghcr.io/michaelsp/timelimit-server/timelimit:latest"
    build:
      context: .
    environment:
      NODE_ENV: production
      DATABASE_URL: mariadb://timelimit:timelimitpassword@database:3306/timelimit
      PORT: 8080
      MAIL_SENDER: me@my.timelimit.server
      MAIL_TRANSPORT: '{"host": "localhost", "port": 25}'
      ALWAYS_PRO: "yes"
      # put additional config variables here
    ports:
      - "8080:8080"
    restart: always
    links:
      - database
  database:
    image: "mariadb:12@sha256:c237fd50cc48d6f2b87c4ca66d52f3b5eef7271b3bea7aee586c0be19d5b460d"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: timelimit
      MYSQL_USER: timelimit
      MYSQL_PASSWORD: timelimitpassword
    volumes:
      - ./.database:/var/lib/mysql
