name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - .github/workflows/helm-chart-publish.yml
      - .github/workflows/release.yml
      - charts/**
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/michaelsp/timelimit-server/timelimit:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
