name: Helm Chart CI

on:
  push:
    branches: [ "master" ]
    paths:
      - .github/workflows/helm-chart-publish.yml
      - charts/**
      
  workflow_dispatch:
  
jobs:
  chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:     
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Add dependency chart repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
