name: PR check

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - run: npm ci
      - run: npm run lint
      - run: npm run build:ts

  helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.1

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          check-latest: true
      - uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
      - name: install helm dependencies
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm dependency update charts/*
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm plugin install https://github.com/helm-unittest/helm-unittest.git

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

        # run helm unittest
      - name: Run helm lint
        if: steps.list-changed.outputs.changed == 'true'
        run: helm lint charts/*
      - name: Run helm unittest
        if: steps.list-changed.outputs.changed == 'true'
        run: helm unittest charts/*
